version: "3"

# 必ずバージョンを記載する必要がある
# task --list-all　で存在するtaskのlistを取得できる
# task gen-proto でcmdを実行できる
tasks:
  gen-proto:
    cmd: protoc --go_out=./ --go_opt=paths=source_relative  --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/health/health_check_service.proto
#  mock-gen-uuid:
#    cmd: mockgen -source=cmd/utils/uuid_utils.go -destination=./cmd/internal/mock/utils/uuid_utils.go -package=utils
#  mock-gen-repo:
#    cmd: mockgen -source=cmd/domain/coffee_repository.go -destination=./cmd/internal/mock/domain/coffee_repository.go -package=mocks
  run-c:
    cmd: cd cmd && go run main.go
